import { TaskProps } from './models/Task.js';

export const seedTasks: TaskProps[] = [
	{
		id: 't_001',
		title: 'Implement Dark Mode',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'Medium Priority',
		status: 'To Do',
		date: '2026-10-28',
		progress: 0,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=1',
	},
	{
		id: 't_002',
		title: 'Implement Dark Mode Toggle',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'Medium Priority',
		status: 'In Progress',
		date: '2026-10-28',
		progress: 45,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=2',
	},
	{
		id: 't_003',
		title: 'Promist t:lear determination',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'High Priority',
		status: 'Done',
		date: '2026-10-28',
		progress: 100,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=3',
	},
	{
		id: 't_004',
		title: 'Implement annoliance',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'Low',
		status: 'To Do',
		date: '2026-10-28',
		progress: 0,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=4',
	},
	{
		id: 't_005',
		title: 'Implement Dark Mode litora',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'Medium Priority',
		status: 'Done',
		date: '2026-10-28',
		progress: 45,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=5',
	},
	{
		id: 't_006',
		title: 'Implement Dark Mode Toggle',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'High Priority',
		status: 'Done',
		date: '2026-10-28',
		progress: 100,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=6',
	},
	{
		id: 't_007',
		title: 'Build login page',
		project: 'Auth Service',
		tag: 'Feature',
		priority: 'High Priority',
		status: 'In Progress',
		date: '2026-10-29',
		progress: 60,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=7',
	},
	{
		id: 't_008',
		title: 'Fix navbar overflow',
		project: 'Web App Redesign',
		tag: 'Bug',
		priority: 'Low',
		status: 'To Do',
		date: '2026-10-30',
		progress: 0,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=8',
	},
	{
		id: 't_009',
		title: 'Write API docs',
		project: 'Internal Tools',
		tag: 'Docs',
		priority: 'Medium Priority',
		status: 'In Progress',
		date: '2026-10-30',
		progress: 30,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=9',
	},
	{
		id: 't_010',
		title: 'Deploy to staging',
		project: 'Web App Redesign',
		tag: 'Ops',
		priority: 'High Priority',
		status: 'Done',
		date: '2026-10-27',
		progress: 100,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=10',
	},
	{
		id: 't_011',
		title: 'Design Dashboard cards',
		project: 'Web App Redesign',
		tag: 'Design',
		priority: 'Medium Priority',
		status: 'Done',
		date: '2026-10-25',
		progress: 100,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=11',
	},
	{
		id: 't_012',
		title: 'Add Pagination component',
		project: 'Web App Redesign',
		tag: 'Feature',
		priority: 'Medium Priority',
		status: 'To Do',
		date: '2026-10-31',
		progress: 10,
		assigneeAvatar: 'https://i.pravatar.cc/64?img=12',
	},
];
